name: Docker Image CI

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
        description: 'The name of the environment to push to.'
    tags:
      - '1.0.0-SNAPSHOT'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SET up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Quarkus application
        run: mvn clean package -Dquarkus.package.type=fast-jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: arzuvbahramov/com.tracker.experience:${{ github.ref_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
